version: 2

sources:
  - name: ipl
    database: DBT 
    schema: DBT_RCHITTIPOLU  # Specify the schema where raw tables are located
    tables:
      - name: raw_players
      - name: raw_teams
      - name: raw_venues
      - name: raw_dismissal_types
      - name: raw_matches
      - name: raw_deliveries
 